<a href="https://colab.research.google.com/github/Abhi-nand/Simple-Linear-Regression/blob/main/SLR1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [9]:
from google.colab import files
uploaded=files.upload()

Saving X.xlsx to X.xlsx
Saving y.xlsx to y.xlsx

In [12]:
df1

    Safety Features  Tech Features  Marketing Spend  Premium Hatchback  SUV
0         165349.20      136897.80        471784.10                  0    1
1         162597.70      151377.59        443898.53                  0    0
2         153441.51      101145.55        407934.54                  1    0
3         144372.41      118671.85        383199.62                  0    1
4         142107.34       91391.77        366168.42                  1    0
5         131876.90       99814.71        362861.36                  0    1
6         134615.46      147198.87        127716.82                  0    0
7         130298.13      145530.06        323876.68                  1    0
8         120542.52      148718.95        311613.29                  0    1
9         123334.88      108679.17        304981.62                  0    0
10        101913.08      110594.11        229160.95                  1    0
11        100671.96       91790.61        249744.55                  0    0
12         93863.75      127320.38        249839.44                  1    0
13         91992.39      135495.07        252664.93                  0    0
14        119943.24      156547.42        256512.92                  1    0
15        114523.61      122616.84        261776.23                  0    1
16         78013.11      121597.55        264346.06                  0    0
17         94657.16      145077.58        282574.31                  0    1
18         91749.16      114175.79        294919.57                  1    0
19         86419.70      153514.11             0.00                  0    1
20         76253.86      113867.30        298664.47                  0    0
21         78389.47      153773.43        299737.29                  0    1
22         73994.56      122782.75        303319.26                  1    0
23         67532.53      105751.03        304768.73                  1    0
24         77044.01       99281.34        140574.81                  0    1
25         64664.71      139553.16        137962.62                  0    0
26         75328.87      144135.98        134050.07                  1    0
27         72107.60      127864.55        353183.81                  0    1
28         66051.52      182645.56        118148.20                  1    0
29         65605.48      153032.06        107138.38                  0    1
30         61994.48      115641.28         91131.24                  1    0
31         61136.38      152701.92         88218.23                  0    1
32         63408.86      129219.61         46085.25                  0    0
33         55493.95      103057.49        214634.81                  1    0
34         46426.07      157693.92        210797.67                  0    0
35         46014.02       85047.44        205517.64                  0    1
36         28663.76      127056.21        201126.82                  1    0
37         44069.95       51283.14        197029.42                  0    0
38         20229.59       65947.93        185265.10                  0    1
39         38558.51       82982.09        174999.30                  0    0
40         28754.33      118546.05        172795.67                  0    0
41         27892.92       84710.77        164470.71                  1    0
42         23640.93       96189.63        148001.11                  0    0
43         15505.73      127382.30         35534.17                  0    1
44         22177.74      154806.14         28334.72                  0    0
45          1000.23      124153.04          1903.93                  0    1
46          1315.46      115816.21        297114.46                  1    0
47             0.00      135426.92             0.00                  0    0
48           542.05       51743.15             0.00                  0    1
49             0.00      116983.80         45173.06                  0    0

In [10]:
df1=pd.read_excel('X.xlsx')
df2=pd.read_excel('y.xlsx')

In [20]:
df=pd.concat([df1,df2],axis=1)
df

,Safety Features,Tech Features,Marketing Spend,Premium Hatchback,SUV,Profit
0,165349.20,136897.80,471784.10,0,1,192261.83
1,162597.70,151377.59,443898.53,0,0,191792.06
2,153441.51,101145.55,407934.54,1,0,191050.39
3,144372.41,118671.85,383199.62,0,1,182901.99
4,142107.34,91391.77,366168.42,1,0,166187.94
5,131876.90,99814.71,362861.36,0,1,156991.12
6,134615.46,147198.87,127716.82,0,0,156122.51
7,130298.13,145530.06,323876.68,1,0,155752.60
8,120542.52,148718.95,311613.29,0,1,152211.77
9,123334.88,108679.17,304981.62,0,0,149759.96
10,101913.08,110594.11,229160.95,1,0,146121.95
11,100671.96,91790.61,249744.55,0,0,144259.40
12,93863.75,127320.38,249839.44,1,0,141585.52
13,91992.39,135495.07,252664.93,0,0,134307.35
14,119943.24,156547.42,256512.92,1,0,132602.65
15,114523.61,122616.84,261776.23,0,1,129917.04
16,78013.11,121597.55,264346.06,0,0,126992.93
17,94657.16,145077.58,282574.31,0,1,125370.37
18,91749.16,114175.79,294919.57,1,0,124266.90
19,86419.70,153514.11,0.00,0,1,122776.86
20,76253.86,113867.30,298664.47,0,0,118474.03
21,78389.47,153773.43,299737.29,0,1,111313.02
22,73994.56,122782.75,303319.26,1,0,110352.25
23,67532.53,105751.03,304768.73,1,0,108733.99
24,77044.01,99281.34,140574.81,0,1,108552.04
25,64664.71,139553.16,137962.62,0,0,107404.34
26,75328.87,144135.98,134050.07,1,0,105733.54
27,72107.60,127864.55,353183.81,0,1,105008.31
28,66051.52,182645.56,118148.20,1,0,103282.38
29,65605.48,153032.06,107138.38,0,1,101004.64
30,61994.48,115641.28,91131.24,1,0,99937.59
31,61136.38,152701.92,88218.23,0,1,97483.56
32,63408.86,129219.61,46085.25,0,0,97427.84
33,55493.95,103057.49,214634.81,1,0,96778.92
34,46426.07,157693.92,210797.67,0,0,96712.80
35,46014.02,85047.44,205517.64,0,1,96479.51
36,28663.76,127056.21,201126.82,1,0,90708.19
37,44069.95,51283.14,197029.42,0,0,89949.14
38,20229.59,65947.93,185265.10,0,1,81229.06
39,38558.51,82982.09,174999.30,0,0,81005.76
40,28754.33,118546.05,172795.67,0,0,78239.91
41,27892.92,84710.77,164470.71,1,0,77798.83
42,23640.93,96189.63,148001.11,0,0,71498.49
43,15505.73,127382.30,35534.17,0,1,69758.98
44,22177.74,154806.14,28334.72,0,0,65200.33
45,1000.23,124153.04,1903.93,0,1,64926.08
46,1315.46,115816.21,297114.46,1,0,49490.75
47,0.00,135426.92,0.00,0,0,42559.73
48,542.05,51743.15,0.00,0,1,35673.41
49,0.00,116983.80,45173.06,0,0,14681.40

In [22]:
df['Expenditure']=df['Safety Features']+df['Tech Features']+df['Marketing Spend']
df

,Safety Features,Tech Features,Marketing Spend,Premium Hatchback,SUV,Profit,Expenditure
0,165349.20,136897.80,471784.10,0,1,192261.83,774031.10
1,162597.70,151377.59,443898.53,0,0,191792.06,757873.82
2,153441.51,101145.55,407934.54,1,0,191050.39,662521.60
3,144372.41,118671.85,383199.62,0,1,182901.99,646243.88
4,142107.34,91391.77,366168.42,1,0,166187.94,599667.53
5,131876.90,99814.71,362861.36,0,1,156991.12,594552.97
6,134615.46,147198.87,127716.82,0,0,156122.51,409531.15
7,130298.13,145530.06,323876.68,1,0,155752.60,599704.87
8,120542.52,148718.95,311613.29,0,1,152211.77,580874.76
9,123334.88,108679.17,304981.62,0,0,149759.96,536995.67
10,101913.08,110594.11,229160.95,1,0,146121.95,441668.14
11,100671.96,91790.61,249744.55,0,0,144259.40,442207.12
12,93863.75,127320.38,249839.44,1,0,141585.52,471023.57
13,91992.39,135495.07,252664.93,0,0,134307.35,480152.39
14,119943.24,156547.42,256512.92,1,0,132602.65,533003.58
15,114523.61,122616.84,261776.23,0,1,129917.04,498916.68
16,78013.11,121597.55,264346.06,0,0,126992.93,463956.72
17,94657.16,145077.58,282574.31,0,1,125370.37,522309.05
18,91749.16,114175.79,294919.57,1,0,124266.90,500844.52
19,86419.70,153514.11,0.00,0,1,122776.86,239933.81
20,76253.86,113867.30,298664.47,0,0,118474.03,488785.63
21,78389.47,153773.43,299737.29,0,1,111313.02,531900.19
22,73994.56,122782.75,303319.26,1,0,110352.25,500096.57
23,67532.53,105751.03,304768.73,1,0,108733.99,478052.29
24,77044.01,99281.34,140574.81,0,1,108552.04,316900.16
25,64664.71,139553.16,137962.62,0,0,107404.34,342180.49
26,75328.87,144135.98,134050.07,1,0,105733.54,353514.92
27,72107.60,127864.55,353183.81,0,1,105008.31,553155.96
28,66051.52,182645.56,118148.20,1,0,103282.38,366845.28
29,65605.48,153032.06,107138.38,0,1,101004.64,325775.92
30,61994.48,115641.28,91131.24,1,0,99937.59,268767.00
31,61136.38,152701.92,88218.23,0,1,97483.56,302056.53
32,63408.86,129219.61,46085.25,0,0,97427.84,238713.72
33,55493.95,103057.49,214634.81,1,0,96778.92,373186.25
34,46426.07,157693.92,210797.67,0,0,96712.80,414917.66
35,46014.02,85047.44,205517.64,0,1,96479.51,336579.10
36,28663.76,127056.21,201126.82,1,0,90708.19,356846.79
37,44069.95,51283.14,197029.42,0,0,89949.14,292382.51
38,20229.59,65947.93,185265.10,0,1,81229.06,271442.62
39,38558.51,82982.09,174999.30,0,0,81005.76,296539.90
40,28754.33,118546.05,172795.67,0,0,78239.91,320096.05
41,27892.92,84710.77,164470.71,1,0,77798.83,277074.40
42,23640.93,96189.63,148001.11,0,0,71498.49,267831.67
43,15505.73,127382.30,35534.17,0,1,69758.98,178422.20
44,22177.74,154806.14,28334.72,0,0,65200.33,205318.60
45,1000.23,124153.04,1903.93,0,1,64926.08,127057.20
46,1315.46,115816.21,297114.46,1,0,49490.75,414246.13
47,0.00,135426.92,0.00,0,0,42559.73,135426.92
48,542.05,51743.15,0.00,0,1,35673.41,52285.20
49,0.00,116983.80,45173.06,0,0,14681.40,162156.86

In [23]:
X=df.iloc[:,-1].values
y=df.iloc[:,-2].values
X,y

(array([774031.1 , 757873.82, 662521.6 , 646243.88, 599667.53, 594552.97,
        409531.15, 599704.87, 580874.76, 536995.67, 441668.14, 442207.12,
        471023.57, 480152.39, 533003.58, 498916.68, 463956.72, 522309.05,
        500844.52, 239933.81, 488785.63, 531900.19, 500096.57, 478052.29,
        316900.16, 342180.49, 353514.92, 553155.96, 366845.28, 325775.92,
        268767.  , 302056.53, 238713.72, 373186.25, 414917.66, 336579.1 ,
        356846.79, 292382.51, 271442.62, 296539.9 , 320096.05, 277074.4 ,
        267831.67, 178422.2 , 205318.6 , 127057.2 , 414246.13, 135426.92,
         52285.2 , 162156.86]),
 array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
        156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
        141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
        124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
        108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
         99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
         90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
         71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
         35673.41,  14681.4 ]))

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [27]:
s_model = LinearRegression().fit(X_train.reshape(-1,1), y_train)

In [30]:
print('coefficient of determination:', s_model.score(X_train.reshape(-1,1), y_train))
print('intercept:', s_model.intercept_)
print('slope:', s_model.coef_)

coefficient of determination: 0.7729612160293439
intercept: 24467.16283020047
slope: [0.2139481]

In [50]:
y_pred=s_model.predict(X_test.reshape(-1,1))
X_test,y_test,y_pred

(array([366845.28, 442207.12, 441668.14, 277074.4 , 662521.6 , 553155.96,
        271442.62, 302056.53, 500096.57, 599667.53]),
 array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
         81229.06,  97483.56, 110352.25, 166187.94]),
 array([102953.01183312, 119076.53397527, 118961.22023075,  83746.70302485,
        166212.3973846 , 142813.82699234,  82541.79441951,  89091.58216013,
        131461.87155291, 152764.88881304]))

In [49]:
y_pred2=s_model.predict(X_train.reshape(-1,1))
X_train,y_train,y_pred2

(array([373186.25, 336579.1 , 353514.92, 414917.66, 500844.52, 599704.87,
        533003.58, 127057.2 ,  52285.2 , 325775.92, 498916.68, 268767.  ,
        238713.72, 463956.72, 267831.67, 488785.63, 178422.2 , 580874.76,
        480152.39, 342180.49, 594552.97, 522309.05, 320096.05, 162156.86,
        757873.82, 471023.57, 292382.51, 316900.16, 409531.15, 478052.29,
        356846.79, 531900.19, 239933.81, 536995.67, 296539.9 , 414246.13,
        646243.88, 774031.1 , 135426.92, 205318.6 ]),
 array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
        132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
         97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
        134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
        191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
         90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
        182901.99, 192261.83,  42559.73,  65200.33]),
 array([104309.65028831,  96477.62026375, 100101.00669866, 113238.00598077,
        131621.89403095, 152772.87763492, 138502.26367135,  51650.80879107,
         35653.48179357,  94166.3004773 , 131209.4363345 ,  81969.3506162 ,
         75539.50859637, 123729.81947338,  81769.23854403, 129041.91748148,
         62640.25271695, 148744.21146217, 127194.85222539,  97676.02698646,
        151670.63844166, 136214.18934547,  92951.10310805,  59160.31420112,
        186612.82325628, 125241.75857214,  87021.84400521,  92267.34852909,
        112085.57242482, 126745.53983001, 100813.85393965, 138266.19548224,
         75800.54452822, 139356.36372395,  87911.309678  , 113094.33341619,
        162729.81019135, 190069.6425409 ,  53441.49444502,  68394.68627303]))

In [36]:
r2_score(y_test,y_pred)

0.675383459891653

In [47]:
s_model.predict(np.array([1315.46+115816.21+297114.46]).reshape(-1,1))

array([113094.33341619])

In [40]:
s_model.score(X_test.reshape(-1,1),y_test)

0.675383459891653

In [42]:
s_model.score(X.reshape(-1,1),y)

0.7610412324682496